version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: my_postgres_db
    
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      
    ports:
      - "5432:5432"
      
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    restart: always

volumes:
  postgres_data: